### ISSUE TITLE
English version please?

### ISSUE THREAD

**Issue by Arsalan0098** [sfc9982/AnyConnect-Server#1]
Hello, can you add english version please?
thanks

**Comment by sfc9982** [comment]
Sure!

**Comment by sfc9982** [comment]
@Arsalan0098 uploaded `ocserv-en.sh` but not sure if available, you can try it.

**Comment by sfc9982** [comment]
I found you have been seeking for AnyConnect solutions.

My solution:

- ocserv or anylink for server side
- OpenConnect / AnyConnect for PC, and OC enables you to change route table
- OpenConnect / AnyConnect for Android, you can mannuly compile OC, or download from F-Droid or Google Play

https://f-droid.org/packages/app.openconnect/
https://play.google.com/store/apps/details?id=com.github.digitalsoftwaresolutions.openconnect&hl=en&gl=US

**Comment by dr1361teh** [comment]
Hello,
I got the following error, it seems the server is down ! any solution ?

Connecting to ftp.infradead.org (ftp.infradead.org)|90.155.50.34|:21... failed: Connection timed out.
Connecting to ftp.infradead.org (ftp.infradead.org)|2001:8b0:10b:1236::1|:21... failed: Network is unreachable.
[错误] ocserv 源码文件下载失败 !
