### ISSUE TITLE
Client Connect But no Internet

### ISSUE THREAD

**Issue by alirezashahrokhi** [sfc9982/AnyConnect-Server#10]
hi all dears 
i config and run commands
client is connect but my internet not working when i connect

**Comment by sfc9982** [comment]
Check your firewall?

**Comment by alirezashahrokhi** [comment]
> Check your firewall?
thanks for replay
i use Ubuntu 20 
port 443 is open  with iptables 
how can check ?

**Comment by sfc9982** [comment]
Just turn it off

**Comment by alirezashahrokhi** [comment]
i can disable iptables ?

> Just turn it off

**Comment by sfc9982** [comment]
Maybe you can, and check if nat and tun are ok.

**Comment by alirezashahrokhi** [comment]
> 

nothing changed after :
ufw disable 
when i open google i get this error : 
ERR_NAME_NOT_RESOLVED

**Comment by sfc9982** [comment]
You need to config the DNS server on it.
`sudo vi /etc/resolv.conf`

**Comment by alirezashahrokhi** [comment]
> 

# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad

**Comment by sfc9982** [comment]
It's the default setting, but I don't know why your DNS is down.

You can read [this](https://unix.stackexchange.com/questions/612416/why-does-etc-resolv-conf-point-at-127-0-0-53) to configure a regular DNS address.

**Comment by sfc9982** [comment]
Try `ping www.google.com` ?

**Comment by alirezashahrokhi** [comment]
root@class:~# ping google.com
PING google.com (216.239.38.120) 56(84) bytes of data.
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=1 ttl=113 time=30.8 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=2 ttl=113 time=26.9 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=3 ttl=113 time=30.0 ms
64 bytes from any-in-2678.1e100.net (216.239.38.120): icmp_seq=4 ttl=113 time=33.6 ms

**Comment by sfc9982** [comment]
`ERR_NAME_NOT_RESOLVED` shouldn't appear anymore.
Could you try again on your VPN client?

And what's the DNS server on your VPN client?

**Comment by alirezashahrokhi** [comment]
how i can check my client dns ?

**Comment by alirezashahrokhi** [comment]
i uninstall and install again 
now every thing is worked

**Comment by alirezashahrokhi** [comment]
after any server reboot problem back again 
i think its problem about forwarding port
how can i save permanently network for this script ?

**Comment by sfc9982** [comment]
It's permanatly by default :(
Is it a clean install, maybe some softwares on your server conflicts with OCServ.

**Comment by alirezashahrokhi** [comment]
> It's permanatly by default :( Is it a clean install, maybe some softwares on your server conflicts with OCServ.

i dont have any software i buy vps just for training about script

**Comment by sfc9982** [comment]
i dont know.
