### ISSUE TITLE
ipv4

### ISSUE THREAD

**Issue by The13east** [sfc9982/AnyConnect-Server#11]
Hi 
you really should change the default ipv4 from 192.168.1.0 to something like 192.168.7.0 
if someone install it and dont notice it it'll destroy their connection in windows after disconnecting and they need to restart their pc or re enable their connection to get their internet back

**Comment by sfc9982** [comment]
This is for hosting a VPN server, nobody should run in a sub-VM in Windows.

**Comment by sfc9982** [comment]
You are right, you can raise a Pull-Request.

**Comment by The13east** [comment]
I dont use github much and i couldn't figure out how to raise a pull-request 
I just put it here so if someone ran into the same problem as me they can fix their config and be fine with your script 
loved your eZ solution and menus tnQ very much

**Comment by sfc9982** [comment]
Script already updated.
