### ISSUE TITLE
SSL connection Failure

### ISSUE THREAD

**Issue by hamedvrz** [sfc9982/AnyConnect-Server#12]
I ran a open connect server on ubuntu. TCP port is 443. when I want to connect to VPN with android open connect App, I get :
-SSL connection failure: the operation timed out
-Failed to open HTTPS connection to server IP
-Error obtaining cookie
-VPN terminated with errors

also I don't have access to internet when I connect to server with windows AnyConnect application. (it connects but have no Internet)

**Comment by sfc9982** [comment]
I'm tired, please refer to other issues and google it.
Sorry.

**Comment by sfc9982** [comment]
If you solve it, you can leave solution here, so that others can know if they happen to meet the same problem.
