### ISSUE TITLE
Limited users

### ISSUE THREAD

**Issue by MmdrezaRP** [sfc9982/AnyConnect-Server#14]
Is there any way to limit the connections at the same time for each user?

I mean only one connection connects to a specific user.

**Comment by sfc9982** [comment]
Yes, read the config file and other issues.

**Comment by sfc9982** [comment]
[max-same-clients = 1](https://gitlab.com/openconnect/ocserv/-/issues/223)

**Comment by MmdrezaRP** [comment]
oh yeah
found it, thank you so much for your amazing script.

**Comment by sfc9982** [comment]
See this: https://github.com/mmtaee/ocserv-users-management?auto_subscribed=false&email_source=explore
