### ISSUE TITLE
scheduled expiration 

### ISSUE THREAD

**Issue by MmdrezaRP** [sfc9982/AnyConnect-Server#15]
sudo sed -i '/test2/ s/\$/!/' /etc/ocserv/ocpasswd && echo "test2 is disabled" >> /etc/ocserv/changeslog.text

i'm using this command to disable user automatically in `crontab` 
any better idea?

**Comment by sfc9982** [comment]
Use anylink

**Comment by MmdrezaRP** [comment]
is there any English tutorial for anylink?

**Comment by sfc9982** [comment]
no

**Comment by sfc9982** [comment]
See this: https://github.com/mmtaee/ocserv-users-management
