### ISSUE TITLE
 Current status: installed  but  NOT running

### ISSUE THREAD

**Issue by hiradjaguar** [sfc9982/AnyConnect-Server#16]
Hi i get this massage :
 Current status: installed  but  NOT running

i tried to stop and start ocserv but this is what i get :

[信息] ocserv 启动中...
[错误] ocserv 启动失败

**Comment by sfc9982** [comment]
Try Engish version?

**Comment by hiradjaguar** [comment]
this is english version

**Comment by sfc9982** [comment]
Reboot, Reinstall, Rebuy.
