### ISSUE TITLE
no-route is limited 

### ISSUE THREAD

**Issue by MmdrezaRP** [sfc9982/AnyConnect-Server#18]
as far as I know no-route is limited on 200 lines 
is there any alternative way to restrict/split the client to connect national internet(Iran's network)?
Great Firewall is sensitive to foreign IPs

**Comment by sfc9982** [comment]
You can put your AnyConnect client into docker and expose a SOCKS5 proxy. Then you can use any rules you like.

For users in Iran, my suggestion is that AnyConnect's protocol is easy to detect but unable to decrypt. If you just want to break through the Firewall of Iran, you may try WireGuard, trojan, etc. AnyConnect isn't best solution.

**Comment by MmdrezaRP** [comment]
I mostly use Trojan and Xray protocols to browse in internet but I also play some games that are not that popular 
I think the great firewall detected it's host server as a bad service and blocked it, I can connect to it and play but after a few minutes the connection goes down and I have to relog into the game. Thats what I need the VPN for
 I need stable and low latency to play games that's why I'm using open connect
wiregaurd must be good for gaming if I'm not wrong but i have no idea how to set it up

**Comment by sfc9982** [comment]
You can try tun2sock or SS-TAP for games. I don't know Iran's firewall technology.

**Comment by MmdrezaRP** [comment]
people say that it is the same as china's

**Comment by sfc9982** [comment]
You can try out these VPNs one by one. If you are temp block, do not connect back immediately, it will cause a permanently block.

**Comment by MmdrezaRP** [comment]
thank you so much for your response.
much <3

**Comment by MmdrezaRP** [comment]
> You can try out these VPNs one by one. If you are temp block, do not connect back immediately, it will cause a permanently block.

how would I realise if im temp blocked or not?

**Comment by sfc9982** [comment]
temp block means you can't connect to your VPN, but ok on SSH port or HTTP 80 port. If you are temp blocked, do not make VPN connect for several days.
