### ISSUE TITLE
Add domain

### ISSUE THREAD

**Issue by siamakdals** [sfc9982/AnyConnect-Server#19]
Please add domain support with ssl

**Comment by sfc9982** [comment]
No, I'm lazy

**Comment by sfc9982** [comment]
I think it's supported by ocserv by default.

**Comment by sfc9982** [comment]
You can do it by yourself and raise a pull request :smiley:.

**Comment by MrWijnen01** [comment]
I did it by port forwarding port 443 tcp/udp and then add a record to my domain and point to my public IP so now I enter vpn.mydomain.com
