### ISSUE TITLE
Got error during installation

### ISSUE THREAD

**Issue by dr1361teh** [sfc9982/AnyConnect-Server#2]
Hello,
I got the following error, it seems the server is down ! any solution ?

Connecting to ftp.infradead.org (ftp.infradead.org)|90.155.50.34|:21... failed: Connection timed out.
Connecting to ftp.infradead.org (ftp.infradead.org)|2001:8b0:10b:1236::1|:21... failed: Network is unreachable.
[错误] ocserv 源码文件下载失败 !

**Comment by sfc9982** [comment]
find 
`ftp://ftp.infradead.org/pub/ocserv/ocserv-${ocserv_ver}.tar.xz`  
in script, and change it to  
`http://www.infradead.org/ocserv/download/ocserv-${ocserv_ver}.tar.xz`

**Comment by wartan6** [comment]
hi,
in readme written that tested on centos7.
but when i run "bash ocserv-en.sh" , got this error:
# bash ocserv-en.sh
[ERROR] OS is not supported centos !

my centos version:
  Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-1160.31.1.el7.x86_64
  Architecture: x86-64

**Comment by sfc9982** [comment]
> hi, in readme written that tested on centos7. but when i run "bash ocserv-en.sh" , got this error:
> 
> # bash ocserv-en.sh
> [ERROR] OS is not supported centos !
> 
> my centos version: Virtualization: kvm Operating System: CentOS Linux 7 (Core) CPE OS Name: cpe:/o:centos:centos:7 Kernel: Linux 3.10.0-1160.31.1.el7.x86_64 Architecture: x86-64

You can edit the script and comment out the line which detect unsupported OS.  
Sorry for inconvenience.

**Comment by sfc9982** [comment]
I will fix it ASAP

**Comment by sfc9982** [comment]
You can try english version now, another guy successed on Ubuntu yesterday.
