### ISSUE TITLE
duplicate ocserv.service

### ISSUE THREAD

**Issue by MmdrezaRP** [sfc9982/AnyConnect-Server#22]
Hi there.
i want to use multiple ports to connect to the server.
I've followed a tutorial that says:
"you need to run multiple ocserv processes. It’s very simple. Copy the /lib/systemd/system/ocserv.service to a new file."
but i cant find and copy this file and directory.

**Comment by sfc9982** [comment]
Maybe you can use iptables to reforward ports.

**Comment by MmdrezaRP** [comment]
iptables -t nat -A PREROUTING -p tcp --dport 444 -j REDIRECT --to-port 443
the command in case somebody need it
