### ISSUE TITLE
Radius authentication

### ISSUE THREAD

**Issue by shahnazari** [sfc9982/AnyConnect-Server#23]
ocserv also supports Radius authentication (e.g. through radcli which has to be installed prior to ocserv itself), but your script doesn't support it. 
So my quick tweak after having installed your script was: apt-get install libradcli4 & apt install ocserv  
then replaced the newly set conf with yours, set ip forward and masquerade again, and we are done.
You may kindly fix this on your script.

**Comment by sfc9982** [comment]
I'm preparing for tests 😢 . You raise a PR for this if you are free. Thanks!

**Comment by sfc9982** [comment]
you can use haloradius
