### ISSUE TITLE
Connects but routes no packet

### ISSUE THREAD

**Issue by MmdrezaRP** [sfc9982/AnyConnect-Server#24]
every time after i change the server ip (either v4 and v6) it connects but routes no packet
i have to delete the script and reinstall it
any hints?

**Comment by sfc9982** [comment]
Check your firewall and NAT?

**Comment by MmdrezaRP** [comment]
yes it's about the NAT , this happens after every reboot
what rule should I add?

**Comment by sfc9982** [comment]
To preserve the iptables rule after reboot, you can use one of the following methods:

1. Using iptables-persistent: In some Linux distributions, you can install the `iptables-persistent` package to automatically save and load iptables rules. You can install it using a package manager (e.g., for Debian/Ubuntu, you can run `sudo apt-get install iptables-persistent`), and after adding the rule, run the following command to save the rules:

   ```
   sudo netfilter-persistent save
   ```

   This will save the iptables rules to disk and load them after a reboot.

2. Using a custom script: You can create a custom script to load the iptables rule during system startup. Here's an example script:

   ```bash
   #!/bin/bash
   iptables -t nat -A POSTROUTING -o {your_adapter_name} -j MASQUERADE
   ```

   Add the above rule to the script, then save the script as `iptables.sh` (or any name you prefer). Next, move the script to the appropriate location, such as the `/etc/init.d/` directory, and ensure it has executable permissions. Finally, use the following command to add the script to the startup process:

   ```bash
   sudo update-rc.d iptables.sh defaults
   ```

   This will load the iptables rule during system startup.

Using one of these methods, you can preserve the iptables rule after a reboot.
