### ISSUE TITLE
Add SSL configuration

### ISSUE THREAD

**Issue by deemo021211** [sfc9982/AnyConnect-Server#25]
Add SSL configuration, which can be more secure

**Comment by sfc9982** [comment]
AnyConnect/OpenConnect itself is actually a SSLVPN.

**Comment by deemo021211** [comment]
> AnyConnect/OpenConnect本身实际上是一个SSLVPN。
What I mean is to bind the domain name so that the TLS1.3 protocol can be used.

**Comment by sfc9982** [comment]
> > AnyConnect/OpenConnect本身实际上是一个SSLVPN。
> 
> tls1.3 is more secure than tls1.2.

OpenConnect 的客户端和服务端是支持 TLS 1.3 的，如果你连接有问题的话。可能是配置文件和你服务端环境的问题。

参考：
- https://github.com/cernekee/ics-openconnect/issues/66

**Comment by sfc9982** [comment]
参考 `ocserv.conf` 中的 `tls-priorities` 等配置项
