### ISSUE TITLE
SBL?

### ISSUE THREAD

**Issue by Kaasklontje** [sfc9982/AnyConnect-Server#29]
Hello love the project but how can I enable sign in before login?

**Comment by sfc9982** [comment]
You can use MVC frontend and DB such as Anylink.

**Comment by MrWijnen01** [comment]
bruh cisco anyconnect has it built-in but you need to config the Anyconnect config file but I cannort find it

**Comment by sfc9982** [comment]
> bruh cisco anyconnect has it built-in but you need to config the Anyconnect config file but I cannot find it

The profile of VPN connect is under `C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Profile` in Windows, these profiles are automatically pull down from ocserv server side.

You should modify them in ocserv configuration file.
