### ISSUE TITLE
Data Transfer problem

### ISSUE THREAD

**Issue by wartan6** [sfc9982/AnyConnect-Server#4]
hi.
i install script in Ubuntu and  everything works fine.
i can connect to server but no data transfer...
error in log:
DTLS initialised. DPD 1800, Keepalive 32400
DTLS handshake timed out
DTLS handshake failed: Resource temporarily unavailable, try again.

**Comment by wartan6** [comment]
please close the issue.
data transfer problem return to firewall & iptables rules...

sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 443 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -j MASQUERADE

**Comment by sfc9982** [comment]
Always checks firewall.
