### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by royabaaff** [sfc9982/AnyConnect-Server#9]
hi , thank you for great work , connection on openconnect android app is perfect
but on ios or other ssl aps ther s a problem with connecting 
error : connection timed out
is there any way to solve this problem ?

**Comment by sfc9982** [comment]
Maybe firewall issue?

**Comment by sfc9982** [comment]
If you solve the problem, you can leave the solution here to let others know.
Thanks

**Comment by sfc9982** [comment]
@ramintabiee Using **Cisco Secure Client** or **OpenConnect**?

**Comment by ramintabiee** [comment]
IOS doesn't have OpenConnect
I tested it on [Cisco Secure Client](https://apps.apple.com/us/app/cisco-secure-client/id1135064690)
Is there another client that i can test it on ?
But it works on openconnect android and windows

**Comment by sfc9982** [comment]
Have you changed settings in Cisco Secure Client, such as untrusted servers?

**Comment by ramintabiee** [comment]
Yea 
It says connection timeout

**Comment by sfc9982** [comment]
Have permit port 443 or 4433?

**Comment by ramintabiee** [comment]
Yea the connection works on android and windows but on IOS has problem

**Comment by sfc9982** [comment]
maybe latest iOS block something

**Comment by sfc9982** [comment]
You can try docker version of ocserv, there are many of them on GitHub.
